web:
  build: .
  links:
   - db
  volumes:
   - ./:/app
  command: /usr/bin/tail -f /var/log/dmesg
db:
  image: mysql:5.6.23
  ports:
  - '3306:3306'
  environment:
    MYSQL_DATABASE: dbal_test
    MYSQL_USER: admin
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password
